apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream flask_app {
            server flask-service:5000;
        }
        server {
            listen 80;
            server_name _;
            location / {
                proxy_pass http://flask_app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }